### ISSUE TITLE
Lower Resolution???

### ISSUE THREAD

**Issue by zeldran04** [v002/v002-Camera-Live#107]
**Is your feature request related to a problem? Please describe.**
I noticed that the program can be super resource intensive sometimes. I have a 2019 MacBook Pro however it can only handle so much. My sole purpose of this program is to use it as a webcam, however, it eats up a lot of my cpu. 

**Describe the solution you'd like**
I was wondering if you could provide options to lower the resolution of the output that way it isn't so heavy on the CPU. 1920 x 1080 is kind of too much for what I need. So maybe add a preferences window that allows you to lower the resolution of the image. such as 1280 X 720. This would be such a nice feature.

**Comment by bangnoise** [comment]
Are you using the "stable" version 11? The Canon SDK uses a lot of CPU power for some reason. Lowering the resolution isn't possible.

The [alpha version 13](https://github.com/v002/v002-Camera-Live/releases/download/13/Camera.Live.zip) has much better CPU usage.
