### ISSUE TITLE
Camera Error message (IE: Camera Model is not supported)

### ISSUE THREAD

**Issue by ocervantes18** [v002/v002-Camera-Live#11]
Hello,

I'm trying to connect a Cannon 5D Mark IV camera and once I launch Camera Live, turn on the camera and select the device, I get a "Camera Error" message and it won't go live. Any help?

**Comment by HillAndrewP** [comment]
I too am using a 5D Mark IV, and have a feeling it's simply unsupported? Excited for it to hopefully be covered soon--

Thanks for the awesome app and support for all previous cameras.
<img width="282" alt="screen shot 2017-06-09 at 3 10 32 pm" src="https://user-images.githubusercontent.com/6549794/26990764-cf958654-4d25-11e7-9e37-41d5b7f716d0.png">

**Comment by lsapan** [comment]
@bangnoise thanks for creating this, it works great with other cameras! I know nothing about the Canon SDK or where to get it, but if there are instructions anywhere I'd be happy to try getting the latest SDK up and running to add 5D Mark IV support. Do you have any pointers?

**Comment by vade** [comment]
Updated the issue title for clarification.

**Comment by bangnoise** [comment]
Not really worth putting out an update with the new SDK unless the new SDK also fixes #8

**Comment by HillAndrewP** [comment]
With the most recent Canon software and macOS Sierra 10.12.5, everything Canon + Sierra side works perfectly for me and my 5D Mark IV with a Mid-2015 MacBook Pro (Graphics: Intel Iris Pro 1536 MB).  The only missing piece is Camera Live supporting the 5D Mark IV.

Which is just to say, putting out an update with the new SDK for 5D Mark IV support would indeed be helpful to at least me, and presumably the other people in #8 and #11 who aren't experiencing any issues with the Canon + Sierra software.

**Comment by bangnoise** [comment]
Should work now with the [latest release](https://github.com/v002/v002-Camera-Live/releases). Re-open this issue if not.

**Comment by HillAndrewP** [comment]
I'm still finding the same issue, though if anyone has special order of operations, please let me know.  The list below is my procedure, and typically finds success with pre-5D Mark IV cameras:

1. Downloaded the newest 'Camera Live' (Thanks @bangnoise )
2. Disabled and exited all Canon Software
3. Plugged Camera into USB 3.0
4. Turn Camera On (Idle and Busy for USB connection)
5.1 Open newest Camera Live
5.2 Camera display changes from black, shows computer, recognizes computer connection
5.3 Camera briefly flashes red light for record (though EOS Utility stays red when successfully connected)
5.4 Camera Live status briefly switches to 'Starting' before sticking on 'Camera Error' for Canon EOS 5D Mark IV

Any advice or confirmation if it's working for anyone else?

**Comment by GameBraining** [comment]
Hi all, anyone my canon eos m10 is having issues connecting
![Screenshot 2020-05-14 at 20 48 55](https://user-images.githubusercontent.com/51001076/81979078-54910280-9624-11ea-9d93-b3572a70a48b.png)
