### ISSUE TITLE
Low Resolution at 320p

### ISSUE THREAD

**Issue by justryanliu** [v002/v002-Camera-Live#116]
Hi, 

i was wondering if there's a way to get a higher resolution at 1080p instead of 320p? I am using Camera Live with CamTwist and I could only get 320p resolution. Using the latest alpha 13 version.

Thanks!

**Comment by isarmstrong** [comment]
I'm seeing the same result, looking through the settings to try to find a cause

**Comment by isarmstrong** [comment]
@justryanliu

1. Change your resolution in CamTwist preferences
2. Shut down everything- your camera, CamTwist and Camera Live
3. Start your camera
4. Start Camera Live, wait for it to activate
5. Start CamTwist and add the syphon server

You should now be at the higher resolution.

**Comment by bangnoise** [comment]
Thanks for the solution @isarmstrong. As this is to do with CamTwist, not Camera Live, I'm closing this issue.
