### ISSUE TITLE
Windows  please

### ISSUE THREAD

**Issue by pandacreative** [v002/v002-Camera-Live#119]
Hello, congratulations on the creation. Is there anything like that for Windows? Thanks in advance.

**Comment by koenkooi** [comment]
https://www.usa.canon.com/internet/portal/us/home/support/self-help-center/eos-webcam-utility/

**Comment by bangnoise** [comment]
dup #63

**Comment by bangnoise** [comment]
Canon have released a camera driver for Windows

https://www.usa.canon.com/support/eoswebcamutility
