### ISSUE TITLE
Nikon D5500 not recognized (in any build)

### ISSUE THREAD

**Issue by hvsinc42** [v002/v002-Camera-Live#121]
**PLEASE COMPLETE ALL OF THIS SECTION**

**System:**
 - macOS version: 10.12.16 
 - Camera manufacturer and model: Nikon D5500
 - Camera Live version: Any/All

**Describe the bug**
I have plugged in my Nikon D5500 via USB (Nikon UC-E6), camera is not populating in Camera Live window it says "No Camera". I know the USB connection is working as I am able to see the camera in the Nikon Transfer 2 software and import functionality is working just fine. I tried this on my wifes laptop (MacBook Pro late 2018, OS 10.14.6) and its the same problem. 

**To Reproduce**
1. Go to finder, search "Camera Live"
2. Click on Camera Live
3. No Camera

**Expected behavior**
To be able to see and select my camera in the window.

**Screenshots**

**Additional context**

**Comment by hvsinc42** [comment]
Apologies, looks like Alpha 13 did the trick, I said I tried all the builds which wasn't exactly true, I tried all the non-Alpha builds. Anyhow, looks like its working just fine now. Cheers!

**Comment by bangnoise** [comment]
Great, yep, support for non-Canon cameras only appears in the recent alphas.
