### ISSUE TITLE
Multiple cameras/instances

### ISSUE THREAD

**Issue by mattdscott** [v002/v002-Camera-Live#138]
System:
 - macOS version: [Catalina]
 - Camera manufacturer and model [Canon EOS t3i / Canon EOS t5]
 - Camera Live version [13]

I was running version 11 until about 3 weeks ago when the it kept showing me camera error even after re-installation. I installed version 13 Alpha to try and rectify the issue and it worked without any issue. This solved my issue and I was able to run two instances of the software to allow me to connect to two Canon cameras (one to each instance) to OBS. Last week, it started acting up and will now not connect each camera to a separate instance but both cameras are now showing up on the same instance.

**Comment by bangnoise** [comment]
dup #76 (I have no advice until this is properly supported, sorry)
