### ISSUE TITLE
Not working for Canon 1300D

### ISSUE THREAD

**Issue by CanonUser** [v002/v002-Camera-Live#15]

**Comment by bangnoise** [comment]
This should have been working when you opened this issue. Can you try the [latest build](https://github.com/v002/v002-Camera-Live/releases) and if the issue persists, provide more detail (eg any errors, or a screenshot of the window with the camera connected).

**Comment by Basdhen** [comment]
It's not recognizing my Canon 1300D either.
Mac 10.12.6
Canon 1300D firmware version 1.1.0
Tried it with build #6

Canon 70D working perfectly fine.

**Comment by bangnoise** [comment]
Does the camera show up in Camera Live at all, or is completely ignored?

**Comment by Basdhen** [comment]
The camera is getting completely ignored.

**Comment by bangnoise** [comment]
Can you confirm you don't have EOS Utility (or any other software which might be using the camera) open?

**Comment by Basdhen** [comment]
I do have EOS Utility but the problem was that the WIFI/NFC function was enabled.
It works now. Sorry for the inconvenience

**Comment by bangnoise** [comment]
No problem - useful information thanks, hopefully also the solution for @CanonUser .
