### ISSUE TITLE
Update Cameral for Zoom new version

### ISSUE THREAD

**Issue by luvjc1240** [v002/v002-Camera-Live#156]
**Is your feature request related to a problem? Please describe.**
Zoom has a new updated version that does not allow camera live but only ManyCam
**Describe the solution you'd like**
I would like a new update of camera live that solves that issue

**Describe alternatives you've considered**
I tried using the EOS Webcam Utility Beta for MACOS that work on an older version of zoom but does not work with the latest version and we can no longer use the older version of zoom.

**Additional context**
Please solve that issue.

**Comment by bangnoise** [comment]
This is a problem with Zoom. Contact them for support with their product.
