### ISSUE TITLE
EOS Rebel SL1: No Camera Recognized

### ISSUE THREAD

**Issue by kasiemarie095** [v002/v002-Camera-Live#16]
Does this work with a EOS Rebel SL1? If it does it doesn't recognize my camera. Any advice?

**Comment by bangnoise** [comment]
This camera should work. Does the status just say "No Camera"? Try updating to the [latest build](https://github.com/v002/v002-Camera-Live/releases).

**Comment by bangnoise** [comment]
Please comment if this issue persists with the [latest build](https://github.com/v002/v002-Camera-Live/releases/latest).
