### ISSUE TITLE
Limit rate of pushing frames to the buffer

### ISSUE THREAD

**Issue by scj643** [v002/v002-Camera-Live#165]
Currently with how many frames are being pushed it's causing high CPU usage with the turboJPEG decompression. This is on the libgphoto2 branch. I've been thinking we could do this on an NSTimer interval to control how many frames are fetched.

![image](https://user-images.githubusercontent.com/5656510/85077102-86e7cf80-b18f-11ea-936f-8755c371f4e7.png)

**Comment by bangnoise** [comment]
dup #145
