### ISSUE TITLE
Camera error Nikon D3200

### ISSUE THREAD

**Issue by Frizzacazzi** [v002/v002-Camera-Live#185]
**PLEASE COMPLETE ALL OF THIS SECTION**

**System:**
 - macOS version: 11
 - Camera manufacturer and model Nikon D3200
 - Camera Live version [e.g. 11]

**Describe the bug**
"Camera error" while the camera is plugged in via usb and displaying connected to pc.

**Comment by bangnoise** [comment]
Version 11 only supports Canon cameras.
You could try the latest alpha https://github.com/v002/v002-Camera-Live/releases
