### ISSUE TITLE
Working with Camera Live Source Code to extend functionality 

### ISSUE THREAD

**Issue by amvzo** [v002/v002-Camera-Live#191]
Hello I wanted to ask, if one was wanting to get a different camera working by building the app from source, what would one need to tackle to get a camera recognized? 

I see that the Version 12/13 do recognize for example the Samsung NX1 and since that camera has a Linux OS that there is a decent sized community of interested users, there might be a way to get these NX cameras to work with Camera Live. 

NX1 Community
https://github.com/ottokiksmaler/nx500_nx1_modding
https://github.com/ge0rg/samsung-nx-hacks
https://github.com/KinoSeed/nx500_nx1_modding
https://github.com/jdieter/nx300m-autobackup
https://github.com/fritzchentastig/NX300M-MFW

Libgphoto2 (which supports and recognizes Samsung NX cameras)
https://github.com/gphoto/libgphoto2
https://github.com/gphoto/libgphoto2/blob/master/camlibs/samsung/samsung.c

This is something I was able to pull out of the Camera Live App that did recognize the camera. 

Samsung NX1 / ptp2 / porttype:0x04 / ops:0000 / file:0x0a / folder:0x0e
  main WINDOW / readwrite / Camera and Driver Configuration /  
  {
    actions SECTION / readwrite / Camera Actions /  
    {
      opcode TEXT / readwrite / PTP Opcode /  / 0x1001,0xparam1,0xparam2
    } (actions)
    settings SECTION / readwrite / Camera Settings /  
    status SECTION / readwrite / Camera Status Information /  
    {
      serialnumber TEXT / readwrite / Serial Number /  / SAMSUNG Digital Camera-157291271
      manufacturer TEXT / readwrite / Camera Manufacturer /  / SAMSUNG Electronics Co. Ltd. 
      cameramodel TEXT / readwrite / Camera Model /  / SAMSUNG Digital Camera
      deviceversion TEXT / readwrite / Device Version /  / None
      vendorextension TEXT / readwrite / Vendor Extension /  / microsoft.com:1.0; microsoft.com/WMPPD:11.0; microsoft.com/WMPPD:10.0; tizen.org:2.3; 
    } (status)
    imgsettings SECTION / readwrite / Image Settings /  
    capturesettings SECTION / readwrite / Capture Settings /  
    other SECTION / readwrite / Other PTP Device Properties /  
    {
      d401 TEXT / readwrite / Synchronization Partner /  / Longhorn Sync Engine
      d402 TEXT / readonly / Friendly Device Name /  / AP_NX1(A0:E0:27)
      d404 TEXT / readonly / PTP Property 0xd404 /  / 1
      d407 TEXT / readonly / Perceived Device Type /  / 1
    } (other)
  } (main)

Is there anything in here that can help us? 

Thank you for your time!

**Comment by bangnoise** [comment]
Versions 12 and 13 are from the libgphoto2 branch.

If libgphoto2 has added support for the cameras you want, you should be able to update the version of libgphoto2 used by Camera Live, otherwise you'd have to look at getting support into libgphoto2 first, then update this project to benefit from those changes.

I'm about to archive this project as it's not active, so you won't be able to reply (sorry) - do fork and continue with it if it's useful to you.
