### ISSUE TITLE
EOS 650D/T4i "Camera error"

### ISSUE THREAD

**Issue by VisualBoy** [v002/v002-Camera-Live#2]
I get "Camera Error" message with my T4i, probably because you're using version 2.10 of ESDK.

There is some chances to have a build with version 2.12?

![schermata 2013-10-24 alle 00 32 17](https://f.cloud.github.com/assets/443705/1395029/15941eac-3c33-11e3-867a-4312d263e293.png)

**Comment by pizthewiz** [comment]
Just noting that the EDSDK v2.15 still doesn't send `kEdsStateEvent_Shutdown` to the event handler unless a session is opened - every EDSDK release, I try it out hoping the behavior went back to that in v2.10 and earlier, and overtime I end up sending them another bug report :wink:

**Comment by julienrobert** [comment]
anyone succeeded to make it works with t4i?

**Comment by SlexAxton** [comment]
I can successfully get everything linked and built with v2.15 on 10.10.3 Yosemite, but I get the 'camera error' message.

@VisualBoy or @pizthewiz - is there something specific that you messed with to get things running with the new sdks? Happy to push a fix if I can find one.

**Comment by SlexAxton** [comment]
Alternatively, if someone could point me towards the place that error message comes from, I may be able to dig in. Not a ton of native chops though :/
