### ISSUE TITLE
Not Compatible With Canon 80D

### ISSUE THREAD

**Issue by kgeary83** [v002/v002-Camera-Live#23]
I've tried everything. Camera Live is simply not compatible with the Canon 80D.

**Comment by bangnoise** [comment]
duplicate #22

**Comment by jakebam4th** [comment]
I get the same Camera Error Message

Running mac Mojave 10.14.3
Canon t3i 600d
Camera live Version 9

I've also got Camtwist Version 3.4.2

No luck.. Anyone have an idea?
