### ISSUE TITLE
Multiple Camera feeds

### ISSUE THREAD

**Issue by JonDRichardson** [v002/v002-Camera-Live#24]
This is less of an issue and more of a general question. I'm trying to connect two DSLR cameras through OBS for live streaming. I tried connecting two 5D Mark IIIs to Camera Live (opened two instances of it via Terminal in OS X Sierra), but it only seems to ever want to have one at a time. I also tried it with one 5D and one 7D. Anyone have any guidance? Is this even possible?

**Comment by bangnoise** [comment]
Not sure it's possible, sorry.

**Comment by JonDRichardson** [comment]
I actually managed to find a workaround, at least for my needs. If I run Canon2Syphon, it'll grab one camera and then Camera Live can grab the other. This wouldn't work for folks using non-Canon cameras.
