### ISSUE TITLE
Sound from an external microphone connected to my DSLR

### ISSUE THREAD

**Issue by DeanKappen** [v002/v002-Camera-Live#26]
I've managed to get Camera Live running perfectly on High Sierra, but [OBS](https://obsproject.com) only picks up sound from the internal microphone on my laptop. I have an external microphone mounted to my DSLR and would love to use it's audio. Is there a known fix for this issue?

**Comment by bangnoise** [comment]
Not possible - the camera doesn’t send audio. Connect the external mic directly to the computer.
