### ISSUE TITLE
Problem with 5D Mark 3

### ISSUE THREAD

**Issue by dragonkiat** [v002/v002-Camera-Live#28]
Yesterday I first tried Camera Live on my 5D mark3 and Macbook pro ( Mac Os 10.13.1 ) with no issue at all . But today when I try again , it's not working . There's no video input to OBS although I've repeat every steps many times . 
My issue is , after start up the Camera Live app and switch on my 5D mark3 in video recording mode , the liveview screen on camera body will shut down and keep asking me to press the START/STOP button to re-activate liveview again . But , the liveview can't be activated again unless I unplug the Canon USB cable . The Camera Live can detect 5D mark3 when pluged in but keep displaying ' starting ' on top .
There's no issue at all when using EOS Utility with the original Canon USB cable for live shooting .
Do U have any sollution ? Thank you .

**Comment by bangnoise** [comment]
I don't have access to this camera, but I'd suggest you try with the camera in photo-taking mode.

**Comment by Adrian-Tucker** [comment]
Hi! I connected my 700D and worked perfectly the first time, now I connect it the same way and the camera live app freezes in starting... Any solution?

Cheers!

**Comment by bangnoise** [comment]
@Adrian-Tucker as above, check which mode the camera is in. There are also major issues with the Canon SDK and recent macOS versions, and it's possibly you happen to have hit those.

**Comment by bangnoise** [comment]
Please comment if this issue persists in [the latest release](https://github.com/v002/v002-Camera-Live/releases/latest).
