### ISSUE TITLE
Canon 70D did not appear on Camera Live

### ISSUE THREAD

**Issue by simon220686** [v002/v002-Camera-Live#3]
Hi,

I've plugged my Canon 70D to the mac via USB 3.0 ... Unfortunately, the device is not detected by the app. When I did use a Canon 1100D everything works finde.

How can I make my Canon 70D working with Camera Live?

**Comment by bangnoise** [comment]
Recent versions of the Canon SDK, which Camera Live relies on, are unstable. Unfortunately this means we can't support more recent cameras. If you are a developer and have access to newer versions of the Canon SDK then you can build your own version, and us it at your own risk.

**Comment by bangnoise** [comment]
closing as dup #2
