### ISSUE TITLE
Question re: Resolution should be 720 or 1080?

### ISSUE THREAD

**Issue by elanfr** [v002/v002-Camera-Live#30]
I got Camera Live successfully working on a Mac running Sierra with a Canon Rebel T5i. I am using it with iGlasses. Thank you for making this software and making it available to the public!

With iGlasses it only presents at 720p. Is this normal or can I get it to stream/capture at 1080 with another program? Do you recommend a different intermediary program besides iGlasses that could work better?

**Comment by bangnoise** [comment]
The live streaming resolution from the camera is lower than the recorded resolution. It varies by model, but 720p is probably the resolution from the camera. Try it into any other Syphon client ([Simple Client](https://github.com/Syphon/Simple/releases) would do) to check the resolution if you think iGlasses might be limiting it.
