### ISSUE TITLE
CPU spike

### ISSUE THREAD

**Issue by Jimg3555** [v002/v002-Camera-Live#32]
I get a CPU spike of at least 150% in Activity Monitor when my camera is connected. This causes the fans to go crazy and means that recording video (with audio) is not viable. I'm using OBS and injecting the 5d mk2 into that.

Incidentally, the same happens when using Canon EOS Utility—but only the Live View function, the rest of the app works fine.

Appreciate that this is not strictly an issue with Camera-Live, but any idea why this might be happening or any fixes/workarounds?
—
MacBook pro (15 inch 2017), 2.9ghz Intel Core i7. macOS High Sierra 10.3.2 | Canon EOS 5d mk2

**Comment by bangnoise** [comment]
Afraid this is mostly due to the JPEG decoding involved. You should still have plenty of processing power left over for video recording - I regularly record from my Canon. I'm not sure what you're using to record, but try an alternative.

**Comment by Jimg3555** [comment]
Thanks for the response. Thought this may be the case. I’m using OBS and I think the issue comes from the fact that I’m recording a game being played with a small window showing the canon content bottom left. So essentially the app is recording two streams at the same time. But it’s the camera live one that’s hogging the CPU. I don’t suppose there’s anyway to reduce this?

**Comment by bangnoise** [comment]
This is much improved in [alpha 13](https://github.com/v002/v002-Camera-Live/releases/download/13/Camera.Live.zip) - turns out a large part of it was the Canon SDK.
