### ISSUE TITLE
Camera Error - or Status "Starting" EOS 500D

### ISSUE THREAD

**Issue by farzadprivate** [v002/v002-Camera-Live#33]
Trying to get this to work. I don't know what I changed but earlier I saw the status "ready" - and when clicking on the cam it would say Camera Error. I think that was because EOS UTILITY was running in the background.

MacOS 10.13.3 - but I am about to update to see if issue persists...

Thanks already for any help...

**Comment by farzadprivate** [comment]
Update: Did even last update of macOS and now even eos utility won't connect to Camera. It says: "Failed to communicate with camera - check connections"

**Comment by bangnoise** [comment]
Don't use EOS Utility and Camera Live at the same time. Check the [Troubleshooting](https://github.com/v002/v002-Camera-Live#troubleshooting) section of the Read Me.

**Comment by themufi** [comment]
Same issue here. my device is actually a rebelt t1i. Cam live picks it up as a 500D. Tired everything on the troubleshooting - no luck. It just fails to move beyond camera error

**Comment by megerman** [comment]
Same issue here. I suspect the T1i/500D doesn't actually work on Mac OS - Utility 2 also won't see it.

**Comment by thooams** [comment]
Same error with my camera EOS 500D and without EOS Utility.
<img width="374" alt="Screen Shot 2021-03-09 at 7 57 28 pm" src="https://user-images.githubusercontent.com/1183066/110522889-b372bb80-8111-11eb-8d56-4c0fe4d49483.png">

How to do to fix that?

Mac: Mac Book pro 2019
Os: Big Sur
