### ISSUE TITLE
Camera Live is Not Optimized for Your Mac

### ISSUE THREAD

**Issue by AlfredoBenitez** [v002/v002-Camera-Live#34]
After the last actualization for the mac, camera live sends the message that is not working.  Cna you pleas tell me what can i do, i am making facebook livestreams with a canon 70d and now does not work!

Thanks in advance!
![image](https://user-images.githubusercontent.com/38502810/38941972-47608b98-42f3-11e8-9e21-70f199a2fe57.png)

**Comment by bangnoise** [comment]
What is the message you see?

There are various issues with the Canon SDK and macOS 10.13 which I can't do anything about (short of a complete rewrite without the official Canon SDK).

Have you followed the steps in the Troubleshooting section of the [Readme](https://github.com/v002/v002-Camera-Live#troubleshooting)?

**Comment by vade** [comment]
> Have you followed the steps in the Troubleshooting section of the Readme?

**Comment by bangnoise** [comment]
The "not optimized for your mac" message is unrelated. The app will still open when you dismiss the message.

**Comment by AlfredoBenitez** [comment]
thank you. :D It is working
