### ISSUE TITLE
upgrade to EDSDK 3.8.0

### ISSUE THREAD

**Issue by renebohne** [v002/v002-Camera-Live#36]
Did you try upgrading to EDSDK 3.8.0? I would love to see support for the M50.

from Canon website:
6 March 2018:
EDSDK 3.8.0 is now available to download by members of the developer programme.
EOS M50 / EOS 2000D / EOS 4000D / EOS M100 are supported.
EOS M50 is the first EOS mirrorless camera to support remote shooting function.
EOS M100 doesn't support remote shooting function.

**Comment by bangnoise** [comment]
4 u 👉🏻 [build 9](https://github.com/v002/v002-Camera-Live/releases/latest)

**Comment by renebohne** [comment]
thanks, that's great! Will test it tonight.

**Comment by renebohne** [comment]
quick feedback: M50 does work. I get 1024x576 pixels at around 24fps.
Mac OS X 10.12.3.
