### ISSUE TITLE
Can't connect to my Canon T6i

### ISSUE THREAD

**Issue by Englund1** [v002/v002-Camera-Live#39]
for over 7 months I've only been able to connect to my Canon T6i ONE TIME!!! very frustrating....
I have Camera LIVE and still nothing

**Comment by bangnoise** [comment]
https://github.com/v002/v002-Camera-Live#troubleshooting

If those steps don't help, please provide more details (eg OS and camera firmware version) - but note there are issues with the underlying Canon SDK on macOS Sierra and beyond.

**Comment by bangnoise** [comment]
Hopefully fixed in [the latest release](https://github.com/v002/v002-Camera-Live/releases/latest).
