### ISSUE TITLE
EOS 5D MkIII does not appear

### ISSUE THREAD

**Issue by seamusdemora** [v002/v002-Camera-Live#4]
downloaded camera live ver 4. connected camera to usb port. put camera in live view mode. no video. app reports "no camera". Also have Canon EOS utilities installed, and it works in Live View

**Comment by pizthewiz** [comment]
Yep, like reported in #2 and #3, the 5D MK III requires a newer EDSDK than v002-Camera-Live uses. You could apply for EDSDK access and rebuild the app though.
