### ISSUE TITLE
Camera is "Active" but MacOS cannot access it

### ISSUE THREAD

**Issue by warent** [v002/v002-Camera-Live#41]
My camera appears as "Active" in the app, the camera is powered on and everything, but it's not an option in any apps (e.g. Quicktime, Hangouts, etc.). Is there something I'm missing?

Thanks!

<img width="392" alt="screen shot 2018-08-27 at 7 35 36 pm" src="https://user-images.githubusercontent.com/13342266/44692459-fd529500-aa30-11e8-93cc-afbabf7c3bcf.png">
<img width="173" alt="screen shot 2018-08-27 at 7 35 51 pm" src="https://user-images.githubusercontent.com/13342266/44692462-fe83c200-aa30-11e8-8bb6-89c99ef604e1.png">

macOS Sierra 10.12.6
Rebel t4i Firmware 1.0.5

**Comment by vade** [comment]
That those applications do not support Syphon :) Syphon applications are an eco-system of opt-in software tools. Google Hangouts and Quicktime have not been extended to support Syphon.

**Comment by bangnoise** [comment]
[CamTwist](http://camtwiststudio.com) might help - I haven't tried it myself but people seem to use it.

**Comment by mallton** [comment]
bangoise is right, you need CamTwist. Once installed, click on View -> Main Window -> Click on Syphon and then click on Select. In the Settings column select CamTwist in the drop down list of Syphon Server options.

Then, in whatever app you open, you will simply change the camera source to CamTwist.

More info and screenshots here: [https://www.lightscameralive.com/blog/how-to-use-a-dslr-camera-to-make-your-live-video-magical](url)
