### ISSUE TITLE
Crashes during Facebook Live - Canon 70D

### ISSUE THREAD

**Issue by whoshoots** [v002/v002-Camera-Live#43]
Hi,

So CameraLive crashes after about 2 minutes of use into Facebook Live. No SD card in camera.

Just spent $100 on ECamm Live, and now feels like a complete waste of money because this App isn't working and it is the only way to connect a DSLR.

*sigh*

Any advice or help?

**Comment by bangnoise** [comment]
Please respond with the requested details if this issue persists with [the latest release](https://github.com/v002/v002-Camera-Live/releases/latest).
