### ISSUE TITLE
Canon t3i is 4:3 aspect ratio

### ISSUE THREAD

**Issue by servantworker** [v002/v002-Camera-Live#44]
T3i shows a cropped 4:3 image when a 16:9 setting is selected, both 1280x720 and 1920x1080 (seen in both Camtwist and Syphon Recorder).

**Comment by bangnoise** [comment]
Do you see a full 16:9 image with black borders to make it 4:3 or a cropped 16:9 image (no black borders, edges missing)?

Camera Live just emits what the camera sends it, which generally corresponds to the image shown in Live View on the camera.

**Comment by delphiy** [comment]
I am getting black bars left and right side quicktime - Mac

**Comment by bangnoise** [comment]
What do you mean by QuickTime? What's your workflow? Camera Live > ?

**Comment by bangnoise** [comment]
CamTwist outputs at a fixed resolution (see CamTwist > Preferences... > General > Video Size). To eliminate the bars, set that resolution to match the output from the camera. The Syphon [Simple Client](https://github.com/Syphon/Simple/releases/tag/5) will display the resolution for a server - to eliminate the bars from CamTwist, match the size Simple Client reports.

**Comment by delphiy** [comment]
I have set 1920 x 1080 in camtwist preferences.
 My camera is canon dslr 4000d , what resolution should I set in camtwist. 
Black bars still there

**Comment by bangnoise** [comment]
From the README (please read it before posting)

> The camera sends the image used for Live View - the dimensions will not match the camera's movie recording settings.

From literally the post you replied to:

> The Syphon Simple Client will display the resolution for a server - to eliminate the bars from CamTwist, match the size Simple Client reports.

**Comment by delphiy** [comment]
Make it simple please ,
My camera canon d4000 . I am not sure how I can get image resolutions 

What resolution values should I put in camtwist

**Comment by bangnoise** [comment]
1. Connect camera, start Camera Live
2. Download [Simple Client](https://github.com/Syphon/Simple/releases/download/5/Syphon.Simple.Apps.zip)
3. Open Simple Client, your camera should be displayed - if not, select it from the menu in the toolbar
4. Read the dimensions from the status display in Simple Client's toolbar
5. Set those values in CamTwist > Preferences... > General > Video Size > Custom

This is a CamTwist usage issue, please contact them for further support.
