### ISSUE TITLE
Canon 750D Stuck on Starting and very RARELY it Activates

### ISSUE THREAD

**Issue by stXwinter** [v002/v002-Camera-Live#46]
This is starting to get f****** annoying now im getting sick of it.

**Comment by stXwinter** [comment]
![screen shot 2018-11-05 at 8 08 12 pm](https://user-images.githubusercontent.com/44768100/47988525-8a535200-e136-11e8-8bab-d29f2a524be6.png)

Have been trying for a straight hour, nothing ffs

**Comment by bangnoise** [comment]
dup #45
