### ISSUE TITLE
Canon EOS R not working on Mac

### ISSUE THREAD

**Issue by WonderWomansGirlfriend** [v002/v002-Camera-Live#48]
Hey!! Ive been trying for the longest time to get my Canon EOS R connected on 2 different systems but it is not going active.  Is the new EOS R supported is that why it's not working?   If not when will you be adding support?  Thanking you in advance. Cheers Faith

**Comment by xjohnson2018** [comment]
Good morning, 
 This seems to be a problem widespread problem possibly with the update of MacOS. Just a heads up.

**Comment by WonderWomansGirlfriend** [comment]
oh ok cool thanks for letting me know!! 👍

**Comment by dank81** [comment]
If you're stuck with Camera Live saying "starting", try deleting any stored images from the camera's memory card. That worked for me with my 5D Mk IV.

**Comment by Snooz82** [comment]
I have also an EOS R and it does not work.
macOS Mojave

**Comment by xjohnson2018** [comment]
The following has worked for me:
Plug DSLR in (turned off)
Open Camera Live
Turn DSLR on
If camera live automatically selects your camera (highlighting it blue) turn DSLR off and wait for DSLR to become unlisted
Turn DSLR Back on wait
DSLR should be "unselected"
Double click DSLR (not single click)

**Comment by DarrinJasz** [comment]
I had a similar issue of it working only about 10% on the time on Mojave.  I ultimately had to buy another Mac and down-grade it to High Sierra for it to work. Hopefully someone is working on a fix :-)

**Comment by bangnoise** [comment]
The EOS R is supported in [the latest release](https://github.com/v002/v002-Camera-Live/releases/latest).

**Comment by Snooz82** [comment]
Awesome! 😎
