### ISSUE TITLE
Canon M50 thin micro HDMI to MacBook Pro

### ISSUE THREAD

**Issue by jkn1114** [v002/v002-Camera-Live#50]
I have my thin micro HDMI cable connected to from my Canon M50 to my MacBook Pro mid 2018 15 inch. The camera live doesn't even detect it. I purchased this cable because I want to go from the thin micro USB to HDMI for higher quality. I have no idea why the camera live is not detecting the camera. I did all of the normal steps as I do each time. ANY help would be greatly appreciated. Or I'll have to simply return the cable to Best Buy and be stuck with less video quality.

**Comment by dank81** [comment]
Camera Live runs over USB only. It doesn’t run over HDMI.

If you want to use HDMI, you need an HDMI capture device like the BlackMagic Designs Mini Recorder.

**Comment by dank81** [comment]
... and if you use that, you don’t need Canon Camera Live nor Camera Live Syphon (i.e. this project)
