### ISSUE TITLE
CANON R NEEDS AN UPDATE ON CAMERA LIVE TO BE RECOGNIZED ON MOJAVE

### ISSUE THREAD

**Issue by briancowen** [v002/v002-Camera-Live#52]
Hi there I'm looking to use my Canon R on Ecamm Live to record new church sermons on sunday morning with Camera live BUT Camera Live does not recognize My Canon R because It hasn't been updated To work on lastest Mojave OS:-) Please help a brother out and update the software. I would LOVE LOVE TO be a geanie Pig if you need to figure out thank you so much in advance!

**Comment by bangnoise** [comment]
...
