### ISSUE TITLE
Weird aspect ratio/resolution problem with OBS and syphon client input with Camera Live?

### ISSUE THREAD

**Issue by DrConflict** [v002/v002-Camera-Live#54]
![Screenshot 2019-06-17 at 00 55 27](https://user-images.githubusercontent.com/48632976/59570658-f10cf680-909b-11e9-92ee-0a1fe0456781.png)
Hi all,

First off, this is a really amazing project. But I have problems in OBS with the
syphon client and Camera Live. Everything shows fine but the aspect ratio
or resolution it wrong. I checked my settings on my EOS 550D and it's outputting
at 1080p 30fps. I can't fill the screen with the Camera Live input. Anyone know
what the problem could be here?

Using Mojave 10.14.5 and OBS 23.2.1. Camera Live v9 as well.

**Comment by bangnoise** [comment]
Camera settings for resolution don't apply to the output from Camera Live - the camera is sending the image used for its Live View - which is typically smaller and squarer than 1080p.
