### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by bakertaylor28** [v002/v002-Camera-Live#63]
This needs a port to Microsoft Windows. It is essential that open source software be available on the Windows platform.

**Comment by swinster** [comment]
+1

**Comment by jandestiny** [comment]
+1, is there any update on this topic? I'd love to use this on my PC

**Comment by vade** [comment]
you're free to implement it @bakertaylor28

**Comment by aubincspitzer** [comment]
+1 for windows as well or even Linux would be amazing. I know nothing about porting between OSs but it might be slightly simpler being both UNIX based. I have nothing Apple/Mac but would really like to use this.

**Comment by bangnoise** [comment]
Canon have released a camera driver for Windows

https://www.usa.canon.com/support/eoswebcamutility

**Comment by MrTomek** [comment]
do you have anything for sony?
