### ISSUE TITLE
Canon 80D "No camera"

### ISSUE THREAD

**Issue by dcajuste** [v002/v002-Camera-Live#69]
Hello peeps!

I am super new to this and I hope I am not annoying with this potentially simple question. I am using an Elgato h60S Capture to use my Canon as a Webcam. I was guided to download Camera Live and then Cam twist. However, When plugging in the Camera for Camera Live nothing comes up. Period. 

I have used Game Capture HD from Elgato and I go get a signal. So I am not sure if its just with Camera Live? I have used two different computers to test this out. Still nothing.

Also, I am using both computers with MacOS Catalina. As If have spent many hours yesterday doing some research. It seems that this new software has caused quite the issue with many cameras as well as this application. So I am not sure if there is a way around it. Thank you again!

I really appreciate your time and patience.

Best,
D

**Comment by bangnoise** [comment]
The Elgato is for HDMI capture (from your camera's HDMI output). Camera Live is for USB capture from the USB connection.

Connect the camera via USB.

Yes there are a lot of problems with the official Canon SDK. I've just put out an alpha build using an alternative library - you may want to try it instead - https://github.com/v002/v002-Camera-Live/releases/download/12/Camera.Live.zip

**Comment by bangnoise** [comment]
Closing this issue as it sounds like you were connecting via HDMI.
