### ISSUE TITLE
Testing new version

### ISSUE THREAD

**Issue by dantaylorseo** [v002/v002-Camera-Live#72]
So far so good on the new version.

Can move camera, play with USB cable, remove cable and reattach. All works fine.

Will use in work tomorrow and see how I go.

**Comment by bangnoise** [comment]
Excellent, thanks for the prompt feedback

**Comment by dantaylorseo** [comment]
No problem, great work!

**Comment by bangnoise** [comment]
Closing this as there isn't an issue (yet?) - feel free to comment/reopen it if you run into problems
