### ISSUE TITLE
Multiple Canon M200 on Mac

### ISSUE THREAD

**Issue by FryMinis** [v002/v002-Camera-Live#78]
Hi! Thank you for this awesome software! I could use some help because I am _**very**_ dumb. I recently got a second Canon M200 camera to use with OBS. Both are plugged in via USB.

- When I only have one camera plugged in, everything is great.
- When I have both cameras plugged in, I get identical listing in Camera Live and can only activate one at a time. Is this normal? I was using Version 11 and it would show "Canon M200" twice. I just upgraded to the Version 13 Alpha and now see "USB PTP Class Camera" twice.

Screenshot:
<img width="376" alt="Screen Shot 2020-03-26 at 11 09 08 PM" src="https://user-images.githubusercontent.com/62735029/77720984-84724100-6fb7-11ea-85fe-3b53cb8ad7e3.png">

Can you please help this dope understand how to make two cameras work at the same time?

**Comment by bangnoise** [comment]
I'm aiming to add support for multiple cameras in the near future - see #76
