### ISSUE TITLE
slow motion

### ISSUE THREAD

**Issue by jhonathanmerkas** [v002/v002-Camera-Live#84]
I connect a canon t5 works for me but the visualization looks like in slow motion

**Comment by bangnoise** [comment]
As you've somehow avoided the bug report template, please can you add the following:

 - macOS version: [e.g. 10.15.3 - see Apple menu > About This Mac]
 - Camera manufacturer and model [e.g. Canon EOS 7D]
 - Camera Live version [e.g. 11]


**Additional context**

**Comment by bangnoise** [comment]
Closing this for lack of info, assume same issue as #92 or #75
