### ISSUE TITLE
Canon EOS M6 'Camera Error'

### ISSUE THREAD

**Issue by harrycallaghan22** [v002/v002-Camera-Live#94]
**PLEASE COMPLETE ALL OF THIS SECTION**

**System:**
 - macOS version: 10.13.6
Canon EOS M6
Camera Live Version 13

**Describe the bug**

**To Reproduce**
1. Go to camera live app and open
2. Turn on camera 
3. App states 'starting' 
4. App detects camera 
5. App states 'camera error'

**Expected behavior**
I was expecting the app to state 'Active' and not 'Camera error'
![Screen Shot 2020-04-07 at 15 05 23](https://user-images.githubusercontent.com/63301236/78678710-3e837a00-78e1-11ea-93a8-80ca4cf625d1.png)

**Screenshots**

**Additional context**

**Comment by bangnoise** [comment]
dup #79
